addr: "0.0.0.0:8080"
home: "."
https:
  domain: ""
  cert: ""
  key: ""

any:
  enable: true
  paths:
    - path: "/path1/to/read"
      mode: "r"
    - path: "/path1/to/write"
      mode: "w"

users:
  - username: "admin"
    password: "admin"
    paths:
      - path: "/path1/to/write"
        mode: "w"
  - username: "long"
    password: "longxxx"
    paths:
      - path: "./long"
        mode: "r"

